# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-29 18:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='karname',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(null=True, upload_to='karname/')),
            ],
        ),
        migrations.CreateModel(
            name='karname_time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='karname',
            name='time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userP.karname_time'),
        ),
        migrations.AddField(
            model_name='karname',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
