# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-24 18:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20160724_2248'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name']},
        ),
        migrations.AlterOrderWithRespectTo(
            name='tag',
            order_with_respect_to=None,
        ),
    ]
