# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-24 18:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20160724_2251'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'pizza'},
        ),
    ]
