# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-25 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_auto_20160724_2302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='gallery',
        ),
        migrations.RemoveField(
            model_name='post',
            name='main_pic',
        ),
        migrations.AddField(
            model_name='post',
            name='main_pic',
            field=models.FileField(null=True, upload_to='images/'),
        ),
    ]
