# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-29 10:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_auto_20160729_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='subs',
        ),
        migrations.AddField(
            model_name='group',
            name='sub',
            field=models.ManyToManyField(blank=True, to='post.subgroup'),
        ),
    ]
