# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-29 20:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_auto_20160729_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='email',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
