# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-27 20:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_auto_20160815_0012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='sub',
        ),
        migrations.RemoveField(
            model_name='post',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
        migrations.DeleteModel(
            name='group',
        ),
        migrations.DeleteModel(
            name='subgroup',
        ),
        migrations.DeleteModel(
            name='tag',
        ),
    ]
